### PR TITLE
rusherhack

### PR DESCRIPTION
**Pull request by HausemasterIssue**
john encode all your shit, not just your password. and encode it from askii or something to base64 or something.

### CODE REVIEW

**Comment by Sxmurai** [comment]
have you tested this?

**Comment by HausemasterIssue** [comment]
no, how tf would u even test a rat lol?

**Comment by Sxmurai** [comment]
by using it yourself? how else do you think i got the readme screenshots lol.

**Comment by HausemasterIssue** [comment]
:/

**Comment by master7720** [comment]
0_o

**Comment by Sxmurai** [comment]
When you can confirm it works, then I'll accept.

**Comment by master7720** [comment]
i can say dis does work!

**Comment by Nutelaspaceman** [comment]
> 
I tried it w/ some friends, it just crashes your game and doesn't give shit, my friend tested it i didnt

**Comment by Sxmurai** [comment]
On the rusherhack pr? If ur talking about the rat itself it's not entirely
done yet

**Comment by Sxmurai** [comment]
Perry had already done this, sorry.

**Pull request closed without merging**
