### PR TITLE
Update JSONRegexHandler.java

### PR DESCRIPTION
**Pull request by hard-shutdown**
google the difference between ```encrypt``` and ```encode``` doofus.

### CODE REVIEW

**Comment by Sxmurai** [comment]
I didn't write that comment, I'll merge when I get home

**Comment by hard-shutdown** [comment]
discord?

**Comment by Sxmurai** [comment]
@hard-shutdown aesthetical#5241

**Comment by hard-shutdown** [comment]
ikr it was needed. I might code a version of this in c++, should I?

**Pull request merged**
